-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.employee
(
    id integer NOT NULL DEFAULT nextval('employee_id_seq'::regclass),
    address character varying(255) COLLATE pg_catalog."default",
    birthdate timestamp without time zone,
    dni character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    names character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(255) COLLATE pg_catalog."default",
    surnames character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_status smallint,
    CONSTRAINT employee_pkey PRIMARY KEY (id),
    CONSTRAINT uk_gwcmllong7g1rcmikpkebtgm3 UNIQUE (dni)
);

CREATE TABLE IF NOT EXISTS public.employee_user
(
    idemployeeuser integer NOT NULL DEFAULT nextval('employee_user_idemployeeuser_seq'::regclass),
    id_employee integer NOT NULL,
    id_user integer NOT NULL,
    CONSTRAINT employee_user_pkey PRIMARY KEY (idemployeeuser)
);

CREATE TABLE IF NOT EXISTS public.employee_vaccine
(
    idemployeevacine integer NOT NULL DEFAULT nextval('employee_vaccine_idemployeevacine_seq'::regclass),
    date timestamp without time zone,
    numberdoses integer,
    id_employee integer,
    id_typevaccine integer,
    CONSTRAINT employee_vaccine_pkey PRIMARY KEY (idemployeevacine)
);

CREATE TABLE IF NOT EXISTS public.genstatus
(
    id integer NOT NULL DEFAULT nextval('genstatus_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT genstatus_pkey PRIMARY KEY (id),
    CONSTRAINT uk_e6ku0srfd03skg0jf3y6kd0au UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.role
(
    id integer NOT NULL DEFAULT nextval('role_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT role_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.type_vaccine
(
    id integer NOT NULL DEFAULT nextval('type_vaccine_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT type_vaccine_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_role
(
    id_user integer NOT NULL,
    id_role integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    password character varying(255) COLLATE pg_catalog."default",
    username character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.employee
    ADD CONSTRAINT fk_genestatus FOREIGN KEY (id_status)
    REFERENCES public.genstatus (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employee_user
    ADD CONSTRAINT fk_employee FOREIGN KEY (id_employee)
    REFERENCES public.employee (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employee_user
    ADD CONSTRAINT fk_users FOREIGN KEY (id_user)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employee_vaccine
    ADD CONSTRAINT fk_employee FOREIGN KEY (id_employee)
    REFERENCES public.employee (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employee_vaccine
    ADD CONSTRAINT fk_typevaccine FOREIGN KEY (id_typevaccine)
    REFERENCES public.type_vaccine (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_role
    ADD CONSTRAINT fk2aam9nt2tv8vcfymi3jo9c314 FOREIGN KEY (id_role)
    REFERENCES public.role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_role
    ADD CONSTRAINT fkr53t650tbjk5yipcm228wf1nc FOREIGN KEY (id_user)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;